### ISSUE TITLE
Multi-threading 

### ISSUE THREAD

**Issue by SuadHus** [SOEP-Group/SOEP#3]
Find a way, to spread the calculations on multiple threads, to make it faster and to utilize the all the cores.

**Comment by SuadHus** [comment]
Of course this is related to the c++ computation part 🤔🤔🤔🤔🤔🤔

**Comment by RyuTribal** [comment]
This should be done in HTML tbh

**Comment by SuadHus** [comment]
certainly

**Comment by RyuTribal** [comment]
#11

**Comment by RyuTribal** [comment]
#11 merged into main
