### ISSUE TITLE
Investigate Potential mutex error

### ISSUE THREAD

**Issue by SuadHus** [SOEP-Group/SOEP#52]
There might a race condition happening in the code while processing the data from the API. I will either make a new PR with fix or deem this as a non problem.

**Comment by syko240** [comment]
@SuadHus Does this impact the number of entries stored in the db for each satellite id? Because I have noticed that it does not store if we set the STOP_TIME=1440 and STEP_SIZE=1, then not always get all 1440 entries in the db, is this related?

**Comment by SuadHus** [comment]
We shall see

**Comment by SuadHus** [comment]
YEP  this was the issue unofrtunately
